CREATE TABLE `abraconc_elifiss`.`Coaxial_cables_02052019` (
  `no` INT(11) NOT NULL,
  `DigiKeyPartNumber` VARCHAR(45) NULL,
  `ManufacturerPartNumber` VARCHAR(45) NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `QuantityAvailable` INT(11) NULL,
  `UnitPriceUSD` DECIMAL(20,4) NULL,
  `MinimumQuantity` INT(11) NULL,
  `Series` VARCHAR(45) NULL,
  `PartStatus` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  `Style` VARCHAR(45) NULL,
  `1stConnector` VARCHAR(45) NULL,
  `2ndConnector` VARCHAR(45) NULL,
  `Length` VARCHAR(45) NULL,
  `CableType` VARCHAR(45) NULL,
  `Impedance` VARCHAR(45) NULL,
  `FrequencyMax` VARCHAR(45) NULL,
  `Color` VARCHAR(45) NULL,
  `Features` VARCHAR(45) NULL,
  `OperatingTemperature` VARCHAR(45) NULL,
  PRIMARY KEY (`no`));