CREATE TABLE `abraconc_elifiss`.`oscillators_digikey_04122019` (
  `no` INT(11) NOT NULL,
  `DigiKeyPartNumber` VARCHAR(45) NULL,
  `ManufacturerPartNumber` VARCHAR(45) NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `QuantityAvailable` INT(11) NULL,
  `UnitPriceUSD` DECIMAL(20,4) NULL,
  `MinimumQuantity` INT(11) NULL,
  `Packaging` VARCHAR(45) NULL,
  `Series` VARCHAR(45) NULL,
  `PartStatus` VARCHAR(45) NULL,
  `BaseResonator` VARCHAR(45) NULL,
  `Type_` VARCHAR(45) NULL,
  `Frequency` VARCHAR(45) NULL,
  `Function_` VARCHAR(45) NULL,
  `Output` VARCHAR(45) NULL,
  `VoltageSupply` VARCHAR(45) NULL,
  `FrequencyStability` VARCHAR(45) NULL,
  `AbsolutePullRange` VARCHAR(45) NULL,
  `OperatingTemperature` VARCHAR(45) NULL,
  `CurrentSupply` VARCHAR(45) NULL,
  `Ratings` VARCHAR(45) NULL,
  `MountingType` VARCHAR(45) NULL,
  `PackageCase` VARCHAR(45) NULL,
  `SizeDimension` VARCHAR(45) NULL,
  `HeightSeated` VARCHAR(45) NULL,
  PRIMARY KEY (`no`));