CREATE TABLE `abraconc_elifiss`.`RF_antennas_11212018` (
  `no` INT(11) NOT NULL,
  `DigiKeyPartNumber` VARCHAR(45) NULL,
  `ManufacturerPartNumber` VARCHAR(45) NULL,
  `Manufacturer` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `QuantityAvailable` INT(11) NULL,
  `UnitPriceUSD` DECIMAL(20,4) NULL,
  `MinimumQuantity` INT(11) NULL,
  `Packaging` VARCHAR(45) NULL,
  `Series` VARCHAR(45) NULL,
  `PartStatus` VARCHAR(45) NULL,
  `FrequencyGroup` VARCHAR(45) NULL,
  `Frequency` VARCHAR(100) NULL,
  `FrequencyRange` VARCHAR(110) NULL,
  `AntennaType` VARCHAR(45) NULL,
  `NumberofBands` VARCHAR(45) NULL,
  `VSWR` VARCHAR(45) NULL,
  `ReturnLoss` VARCHAR(45) NULL,
  `Gain` VARCHAR(45) NULL,
  `PowerMax` VARCHAR(45) NULL,
  `Features` VARCHAR(45) NULL,
  `Termination` VARCHAR(80) NULL,
  `IngressProtection` VARCHAR(45) NULL,
  `MountingType` VARCHAR(45) NULL,
  `Height` VARCHAR(45) NULL,
  `Applications` VARCHAR(100) NULL,
  PRIMARY KEY (`no`));